# Updated:   2026-01-28
# Run:  docker-compose -f docker-qlever-ui.yaml up

services:

  meshczskos-ui:
    build:
      context: ./qlever
    image: adfreiburg/qlever-ui
    container_name: qlever-ui-meshczskos
    working_dir: /data/meshczskos
    volumes:
      - ./data:/data
    ports:
      - "8080:8080"
    command: >
      qlever ui
      --name meshczskos
      --port 8088
      --ui-port 8080
      --ui-system docker
      --ui-config-file QLeverfile-ui.yml
      --log-level WARNING

      #--host-name test.medvik.cz
