# Updated:   2026-02-03
# 1. Build:
# docker-compose -f docker-qlever-ui.yaml --profile staging up --build
# 2. Run:
# docker-compose -f docker-qlever-ui.yaml --profile server up

services:

  qleverui-bootstrap:
    image: adfreiburg/qlever-ui:latest
    container_name: qleverui-bootstrap
    working_dir: /app
    volumes:
      - ./qleverui/data/db:/app/db
    # Create and update the /qleverui/.env file !
    env_file: /qleverui/.env  # Loads credentials from a separate file
    entrypoint: /bin/bash -c
    command: >
      "python manage.py migrate &&
       python manage.py createsuperuser --noinput || true"
    profiles: ["staging"]


  qleverui-server:
    image: adfreiburg/qlever-ui:latest
    container_name: qleverui
    working_dir: /app
    volumes:
      - ./qleverui/data/db:/app/db
    ports:
      - "7000:7000"
    profiles: ["server"]
