# Updated:   2026-01-25
# 1. Build and run:
# docker-compose -f docker-skosmos.yaml up --build
# Re-build:
# docker-compose -f docker-skosmos.yaml up --build --no-cache
# 2. Run:
# docker-compose -f docker-skosmos.yaml up


services:
  skosmos:
    build:
      context: ./skosmos
    image: skosmos-meshcz
    container_name: skosmos-meshcz
    volumes:
      - ./skosmos/logs:/skosmos/logs
    ports:
      - "8080:80"
