# Updated:   2026-01-29
# 1. Build:
# docker-compose -f docker-fuseki.yaml --profile staging up --build
# 2. Run:
# docker-compose -f docker-fuseki.yaml up fuseki

services:
  fuseki-staging:
    build:
      context: ./fuseki
    image: meshcz-fuseki-staging
    container_name: meshcz-fuseki-staging
    environment:
      - MESH_YEAR=2026
      - DATASETS=meshcz-skos|skosmos;meshcz|meshcz
      - FUSEKI_HOME=/apache-jena-fuseki
      - FUSEKI_BASE=/jena-data
      - HOST_IN=/host-data
      - HOST_OUT=/host-data-out
    volumes:
      - ./fuseki/config:/jena-data/configuration:ro
      - ./fuseki/data:/host-data:ro
      - ./fuseki/data:/host-data-out
    entrypoint: ["/meshcz-data-loading.sh"]
    profiles: ["staging"]
    # no command needed; entrypoint does all work


  fuseki:
    build:
      context: ./fuseki
    image: meshcz-fuseki
    container_name: meshcz-fuseki
    environment:
      - FUSEKI_HOME=/apache-jena-fuseki
      - FUSEKI_BASE=/jena-data
    volumes:
      - ./fuseki/config:/jena-data/configuration
      - ./fuseki/data:/jena-data

    ports:
      - "3030:3030"
    command: ["java",
              "-Xms4G",
              "-Xmx4G",
              "--add-modules=jdk.incubator.vector",
              "--enable-native-access=ALL-UNNAMED",
              "-jar",
              "/apache-jena-fuseki/fuseki-server.jar"]
