# Updated:   2026-01-25
# 1. Build and run:
# docker-compose -f docker-skosmos.yaml up --build
# 2. Run:
# docker-compose -f docker-skosmos.yaml up


services:
  skosmos:
    build:
      context: ./skosmos
    image: meshcz-skosmos
    container_name: meshcz-skosmos
    ports:
      - "8080:80"
