# Updated:   2026-01-30
# 1. Build:
# - on a Windows host:
# docker compose --file docker-fuseki.yaml --profile staging-winhost up --build
# - on a linux host:
# docker compose --file docker-fuseki.yaml --profile staging up --build
# 2. Run:
# docker compose --file docker-fuseki.yaml --profile server up fuseki


services:

  fuseki-build:
    image: fuseki-meshcz
    build:
      context: ./fuseki
    profiles: [staging, staging-winhost, server]


  fuseki-staging:
    image: fuseki-meshcz
    depends_on: [fuseki-build]
    container_name: fuseki-staging-meshcz
    environment:
      HOST_PLATFORM: LINUX
      MESH_YEAR: 2026
      DATASETS: meshcz-skos|skosmos
      #DATASETS: meshcz-skos|skosmos;meshcz|meshcz
      #REFRESH_DATA: 1
      #REFRESH_STORE: 1
      FUSEKI_HOME: /apache-jena-fuseki
      FUSEKI_BASE: /jena-data
    volumes:
      - ./fuseki/entrypoints:/fuseki-scripts
      - ./fuseki/config:/jena-data/configuration:ro
      - ./fuseki/data:/jena-data
    entrypoint: ["/bin/bash", "/fuseki-scripts/meshcz-data-loading.sh"]
    profiles: [staging]


  fuseki-staging-winhost:
    image: fuseki-meshcz
    depends_on: [fuseki-build]
    container_name: fuseki-staging-winhost-meshcz
    environment:
      HOST_PLATFORM: WINDOWS
      MESH_YEAR: 2026
      DATASETS: meshcz-skos|skosmos
      #DATASETS: meshcz-skos|skosmos;meshcz|meshcz
      #REFRESH_DATA: 1
      #REFRESH_STORE: 1
      FUSEKI_HOME: /apache-jena-fuseki
      FUSEKI_BASE: /jena-data
      HOST_IN: /host-data
      HOST_OUT: /host-data-out
    volumes:
      - ./fuseki/entrypoints:/fuseki-scripts
      - ./fuseki/config:/jena-data/configuration:ro
      - ./fuseki/data:/host-data:ro
      - ./fuseki/data:/host-data-out
    entrypoint: ["/bin/bash", "/fuseki-scripts/meshcz-data-loading.sh"]
    profiles: [staging-winhost]


  fuseki:
    image: fuseki-meshcz
    depends_on: [fuseki-build]
    container_name: fuseki-server-meshcz
    environment:
      FUSEKI_HOME: /apache-jena-fuseki
      FUSEKI_BASE: /jena-data
    volumes:
      - ./fuseki/config:/jena-data/configuration
      - ./fuseki/data:/jena-data
    ports:
      - "3030:3030"
    command:
      - java
      - -Xms4G
      - -Xmx4G
      - --add-modules=jdk.incubator.vector
      - --enable-native-access=ALL-UNNAMED
      - -jar
      - /apache-jena-fuseki/fuseki-server.jar
      - --ping
      - --stats
      - --compact
    profiles: [server]
