# Updated:  2025-05-05

services:
  fuseki:
    container_name: apache-jena-fuseki
    build:
      context: .
      dockerfile: Dockerfile
    image: fuseki
    ports:
      - "3030:3030"
    volumes:
        - ./configuration:/configuration
