# Updated:   2026-02-03
# 1. Build:
# docker-compose -f docker-qlever-ui.yaml up --build
# 2. Run:
# docker-compose -f docker-qlever-ui.yaml up

services:

  meshczskos-ui:
    build:
      context: ./qlever
    image: adfreiburg/qlever-ui
    container_name: qlever-ui-meshczskos
    working_dir: /qlever/qlever-data/meshczskos
    entrypoint: ["qlever"]
    volumes:
      - ./qlever/data/meshczskos:/qlever/qlever-data/meshczskos
    ports:
      - "8080:8080"
    command: >
      ui
      --name meshczskos
      --port 8088
      --ui-port 8080
      --ui-system docker
      --ui-config-file QLeverfile-ui.yml
      --log-level WARNING

    #--host-name test.medvik.cz
